# Generated by Django 4.1.2 on 2022-10-13 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='motor_speed',
            new_name='MotorSpeed',
        ),
    ]
